basic.forever(function on_forever() {
    pins.analogWritePin(AnalogPin.P0, 255)
    pins.analogWritePin(AnalogPin.P1, 0)
    pins.analogWritePin(AnalogPin.P2, 0)
    basic.pause(500)
    pins.analogWritePin(AnalogPin.P0, 0)
    pins.analogWritePin(AnalogPin.P1, 255)
    pins.analogWritePin(AnalogPin.P2, 0)
    basic.pause(500)
    pins.analogWritePin(AnalogPin.P0, 0)
    pins.analogWritePin(AnalogPin.P1, 0)
    pins.analogWritePin(AnalogPin.P2, 255)
    basic.pause(500)
    pins.analogWritePin(AnalogPin.P0, 255)
    pins.analogWritePin(AnalogPin.P1, 255)
    pins.analogWritePin(AnalogPin.P2, 0)
    basic.pause(500)
    pins.analogWritePin(AnalogPin.P0, 255)
    pins.analogWritePin(AnalogPin.P1, 0)
    pins.analogWritePin(AnalogPin.P2, 255)
    basic.pause(500)
    pins.analogWritePin(AnalogPin.P0, 192)
    pins.analogWritePin(AnalogPin.P1, 255)
    pins.analogWritePin(AnalogPin.P2, 62)
    basic.pause(500)
    pins.analogWritePin(AnalogPin.P0, 148)
    pins.analogWritePin(AnalogPin.P1, 0)
    pins.analogWritePin(AnalogPin.P2, 211)
    basic.pause(500)
    pins.analogWritePin(AnalogPin.P0, 118)
    pins.analogWritePin(AnalogPin.P1, 238)
    pins.analogWritePin(AnalogPin.P2, 0)
    basic.pause(500)
    pins.analogWritePin(AnalogPin.P0, 0)
    pins.analogWritePin(AnalogPin.P1, 197)
    pins.analogWritePin(AnalogPin.P2, 205)
    basic.pause(500)
})
