def on_forever():
    pins.analog_write_pin(AnalogPin.P0, 255)
    pins.analog_write_pin(AnalogPin.P1, 0)
    pins.analog_write_pin(AnalogPin.P2, 0)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 0)
    pins.analog_write_pin(AnalogPin.P1, 255)
    pins.analog_write_pin(AnalogPin.P2, 0)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 0)
    pins.analog_write_pin(AnalogPin.P1, 0)
    pins.analog_write_pin(AnalogPin.P2, 255)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 255)
    pins.analog_write_pin(AnalogPin.P1, 255)
    pins.analog_write_pin(AnalogPin.P2, 0)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 255)
    pins.analog_write_pin(AnalogPin.P1, 0)
    pins.analog_write_pin(AnalogPin.P2, 255)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 192)
    pins.analog_write_pin(AnalogPin.P1, 255)
    pins.analog_write_pin(AnalogPin.P2, 62)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 148)
    pins.analog_write_pin(AnalogPin.P1, 0)
    pins.analog_write_pin(AnalogPin.P2, 211)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 118)
    pins.analog_write_pin(AnalogPin.P1, 238)
    pins.analog_write_pin(AnalogPin.P2, 0)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 0)
    pins.analog_write_pin(AnalogPin.P1, 197)
    pins.analog_write_pin(AnalogPin.P2, 205)
    basic.pause(500)
basic.forever(on_forever)
